# This is a basic workflow to help you get started with Actions

name: Build ISO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command to downnload the Ubuntu ISO image
      - name: Fetch Ubuntu ISO
        run: wget https://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso

      # Runs the installer that builds the ISO
      - name: Run installer
        run: bash create-install.sh


      # Save ISO to GitHub
      - name: Upload ISO artrfact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-autoinstall
          path: ubuntu-24.04.1-live-server-autoinstall.iso
