# This is a basic workflow to help you get started with Actions

name: Build ISO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # 1) Attempt to restore the ISO from cache
      - name: Restore ISO from cache
        uses: actions/cache@v3
        id: iso-cache
        with:
          path: ubuntu-24.04.1-live-server-amd64.iso
          key: ${{ runner.os }}-ubuntuiso-24.04.1

      # 2) Only download the ISO if it's not already cached
      - name: Fetch Ubuntu ISO
        if: steps.iso-cache.outputs.cache-hit != 'true'
        run: |
          wget https://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso -O ubuntu-24.04.1-live-server-amd64.iso

      # 3) Re-save the ISO to the cache if it was just downloaded
      - name: Update ISO cache
        if: steps.iso-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ubuntu-24.04.1-live-server-amd64.iso
          key: ${{ runner.os }}-ubuntuiso-24.04.1

      # Runs the installer that builds the ISO
      - name: Run installer
        run: bash create-install.sh

      # Runs the checksums of Source and Generated ISOs
      - name: Calculates Checksums
        run: |
          sha256sum *.iso > checksum.sha256
          echo "Checksums are:"
          cat checksum.sha256

      # Save ISO and Checksums to GitHub
      - name: Upload ISO artrfact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-autoinstall
          path: |
            ubuntu-24.04.1-live-server-autoinstall.iso
            checksums.sha256
